apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mspsql-system
resources:
- rbac.yaml
- deployment.yaml
- service.yaml
images:
- name: lease-gate
  newName: ghcr.io/sindef/mspsql-gateway
  newTag: latest
- name: wireguard-go
  newName: ghcr.io/sindef/mspsql-wireguard
  newTag: latest
