apiVersion: v1
kind: Service
metadata:
  name: mspsql-wireguard
  annotations:
    external-dns.alpha.kubernetes.io/hostname: wireguard.example.invalid
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector: {app.kubernetes.io/name: mspsql-wireguard}
  ports:
  - {name: wireguard, port: 51820, targetPort: wireguard, protocol: UDP}
