apiVersion: multisite-postgres.dev/v1alpha1
kind: PostgresUpgrade
metadata:
  labels:
    app.kubernetes.io/name: mspsql
    app.kubernetes.io/managed-by: kustomize
  name: orders-pg18
  namespace: database-platform
spec:
  instanceRef: orders
  targetImage: percona/percona-distribution-postgresql:18
  targetMajorVersion: 18
  serviceRestorationTarget: 15m
