apiVersion: multisite-postgres.multisite-postgres.dev/v1alpha1
kind: MultiSitePostgres
metadata:
  labels:
    app.kubernetes.io/name: mspsql
    app.kubernetes.io/managed-by: kustomize
  name: multisitepostgres-sample
spec:
  # TODO(user): Add fields here
