apiVersion: multisite-postgres.dev/v1alpha1
kind: PostgresUser
metadata:
  labels:
    app.kubernetes.io/name: mspsql
    app.kubernetes.io/managed-by: kustomize
  name: orders-application
  namespace: database-platform
spec:
  instanceRef: orders
  roleName: orders_app
  deletionPolicy: Retain
  memberOf:
  - {databaseRef: orders-api, role: orders_rw}
  passwordVaultRef:
    mount: secret
    path: postgres/orders/users/orders-app
    key: password
  quotas:
    connectionLimit: 50
