apiVersion: multisite-postgres.dev/v1alpha1
kind: SiteRegistration
metadata:
  labels:
    app.kubernetes.io/name: mspsql
    app.kubernetes.io/managed-by: kustomize
  name: production-vic
spec:
  displayName: Production VIC
  permittedStorageClasses:
    etcd: [premium-rwo]
    postgres: [premium-rwo]
    restoreWorkspace: [premium-rwo]
  storageRollbackPolicies:
  - storageClassName: premium-rwo
    strategy: VolumeSnapshot
    volumeSnapshotClassName: premium-rwo-retain
  permittedIssuers:
    etcd:
    - {name: etcd-vault, kind: ClusterIssuer, group: cert-manager.io}
    postgres:
    - {name: postgres-vault, kind: ClusterIssuer, group: cert-manager.io}
    pgpool:
    - {name: client-vault, kind: ClusterIssuer, group: cert-manager.io}
    backup:
    - {name: backup-vault, kind: ClusterIssuer, group: cert-manager.io}
  metallbAddressPools: [database-services]
