apiVersion: multisite-postgres.dev/v1alpha1
kind: PostgresRestore
metadata:
  labels:
    app.kubernetes.io/name: mspsql
    app.kubernetes.io/managed-by: kustomize
  name: orders-restore
  namespace: database-platform
spec:
  sourceInstanceRef: orders
  targetInstanceRef: orders-recovered
  targetTime: "2026-07-16T02:15:00Z"
