apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mspsql-agent
resources:
- namespace.yaml
- service_account.yaml
- cluster_role.yaml
- cluster_role_binding.yaml
- deployment.yaml
- network_policy.yaml
images:
- name: site-agent
  newName: ghcr.io/sindef/mspsql-agent
  newTag: latest
- name: wireguard-go
  newName: ghcr.io/wireguard/wireguard-go
  newTag: latest
